apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: memcached-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Memcached is the Schema for the memcacheds API
      displayName: Memcached
      kind: Memcached
      name: memcacheds.cache.mars-crater.com
      specDescriptors:
      - description: Port defines the port that will be used to init the container
          with the image
        displayName: Container Port
        path: containerPort
      - description: Size defines the number of Memcached instances
        displayName: Size
        path: size
      statusDescriptors:
      - description: Conditions store the status conditions of the Memcached instances
        displayName: Conditions
        path: conditions
      version: v1alpha1
  description: memcached operator description
  displayName: memcached
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - memcached
  - operator
  links:
  - name: Memcached Operator
    url: https://memcached-operator.domain
  maturity: alpha
  provider:
    name: mars-crater
    url: mars-creater.com
  version: 0.0.0
